### PR TITLE
Changing sorting method.

### PR DESCRIPTION
**Pull request by Vesnyx**
Seems a little easier for user to see then if it's by the checkbox.

### CODE REVIEW

**Comment by DakuTree** [comment]
Bit confused as the title and what is actually changed in the commit don't seem to match here.

> Changing sorting method

This can already be done via the options page.

> Seems a little easier for user to see then if it's by the checkbox. / Commit

I'm assuming you were trying to move the update time icon here? I'm happy where it is at the moment so going to have to deny this PR.  
Wanting to keep all the series icons together if possible.

**Comment by Vesnyx** [comment]
Woops, I guess I should make my commits a bit more clear.

http://i.imgur.com/6SAyXK5.png

My proposal was to switch the class tables that are currently applied here. The primary column sorts the table by latest update, while the last column title has a clickable button, that doesn't do anything. I wanted the last column to sort by latest update, while changing the first column to do nothing. 

It might just be me, but I don't quite see why a column with a checkbox to pick series also sorts them. 

I've also realized that this might break the sort that is currently implemented in user options, so I can take a look at that if you think this is a good idea.

**Comment by Vesnyx** [comment]
Just in case closed pull requests don't notify. @DakuTree

**Comment by DakuTree** [comment]
> Just in case closed pull requests don't notify. @DakuTree

They do, I'm just terrible at writing up replies in a reasonably speedy manner. :sweat:

> The primary column sorts the table by latest update, while the last column title has a clickable, invisible button that doesn't do anything. I wanted the last column to sort by latest update, while changing the first column to do nothing.

Would prefer to keep the unread sort where it is, and don't really want to mix the unread sort with the user action column if possible.

As for the last column having a clickable invisible button, might be better to look at simply just merging the last two columns, as that is actually how [NovelUpdates](http://i.imgur.com/dl6AqPH.png) handles things.

**Comment by Vesnyx** [comment]
Understood. I'll see if I can work on merging the columns. 

Also, what are your thoughts on adding a secondary way of choosing the list sort on the dashboard?

**Comment by DakuTree** [comment]
> Also, what are your thoughts on adding a secondary way of choosing the list sort on the dashboard?

I'm not against it, but not exactly sure where would be the best place for it to go without it taking more vertical space.

**Pull request closed without merging**
