### PR TITLE
Initial Implementation of Zoom Controls | #120

### PR DESCRIPTION
**Pull request by Vesnyx**
Very, very basic work on zoom controls for user. Currently uses the '+' , '-', and '=' characters with event listeners.
Work on #120

### CODE REVIEW

**Comment by Vesnyx** [comment]
Any advice on what else I should add? 

- [X ] Zoom on buttons
- [ ] Custom buttons (this would be linked to site settings)
- [ ] Better listening mechanism (current method checks on any key press on page)
- [ ] Keep tracking of page placement
- [ ] Not just changing max width?

**Comment by DakuTree** [comment]
Works well. Merged~

Some ideas for what to add/change:
* Buttons would be useful, but not sure if having them on the topbar is the best idea.
* Should probably be scaling by the largest dimension, rather than only width since things like double page spreads exist.
* User should have some kind of feedback that the images have been zoomed in/out.
* Zoom seems to be restricted by the max-width CSS we have. Fairly sure we need this when not zooming for the rare extremely large images though..

**Comment by Vesnyx** [comment]
> Buttons would be useful, but not sure if having them on the topbar is the best idea.

Custom buttons was more of a keybindings thing. So if the user wanted to set custom buttons for controlling image zoom, they could change them on the user options page.

> User should have some kind of feedback that the images have been zoomed in/out.

Should I add some sort of toast notification or modify the topbar?

**Comment by DakuTree** [comment]
> Custom buttons was more of a keybindings thing.

Ah, that would be useful too.

> Should I add some sort of toast notification or modify the topbar?

Toast notification would probably be better.

**Pull request merged**
